NEWS.md, src/gdalraster.cpp, src/gdalraster.h
requesting band-level metadata for a domain other than the default domain was returning dataset-level metadata instead
=> GDALRaster::getMetadata(): fix for band-level metadata when not in the default domain

DESCRIPTION, NEWS.md, R/display.R, R/gdalraster.R, man/GDALRaster-class.Rd, man/gdalraster-package.Rd, man/plot_raster.Rd, vignettes/articles/raster-display.Rmd
Previously, `data`  was a vector of pixel values. It can now be either a vector of data, or a  `GDALRaster` object to read from.
=> plot_raster(): data argument can be a GDALRaster object to read from

src/gdal_exp.cpp
If `GDALWarpAppOptionsNew()` returned a null pointer, the subsequent call to `GDALWarpAppOptionsSetProgress()` passing the null pointer instead of a valid options struct, resulted in segfault. The return value of `GDALWarpAppOptionsNew()`  and also `GDALDEMProcessingOptionsNew()` are now checked.
=> gdal_exp.cpp: check return value from calls to GDAL*OptionsNew()

NEWS.md, R/RcppExports.R, R/gdalraster.R, man/GDALRaster-class.Rd, src/gdalraster.cpp, src/gdalraster.h
Returns the default Raster Attribute Table as a data frame, or NULL if there is no attribute table.
=> add GDALRaster::getDefaultRAT()

NEWS.md, R/display.R, man/plot_raster.Rd
just for consideration ... make plot_raster() be a georeferenced plot by default? 
It means we can always map over the plot we get, i.e. 
```R
library(gdalraster)
ds <- new(GDALRaster, "/vsicurl/https://gebco2023.s3.valeria.science/gebco_2023_land_cog.tif", read_only = TRUE)
plot_raster(ds, 360, 180, interpolate = F)
maps::map(add = T, col = "yellow")
```
=> make plot_raster be georeferenced by default ?

src/Makevars.win
This will use pkg-config to establish the libraries to link when pkg-config is available (which will soon be in Rtools). This should reduce the frequency of needed updates to linking when new features are linked/enabled in gdal.
=> Use pkg-config on Windows when available.

R/display.R, R/gdalraster_proc.R, man/plot_raster.Rd, man/read_ds.Rd, src/wkt_conv.cpp, tests/testthat/test-GDALRaster-class.R, tests/testthat/test-display.R, vignettes/articles/raster-display.Rmd
This pull request modifies the function `read_ds()` (convenience wrapper for the class method `GDALRaster$read()`):
* New argument `as_list` can be set to `TRUE` to return band vectors as list elements (default is pixel data as a single vector, interleaved by band).
* The output object (list or vector) now has attribute `gis`, a list with:
```
$type = "raster"
$extent = c(xmin, ymin, xmax, ymax)
$dim = c(xsize, ysize, nbands)
$srs = <projection as WKT2 string>
```
The function `plot_raster()` is also modified to accept the optional list output from `read_ds()` and make use of `gis` attributes if present. This allows using georeferenced coordinates by default instead of pixel/line in the case of raw pixel input (i.e., when input is not an object of class `GDALRaster` but rather a vector or …
=> Add as_list argument in read_ds() and attach gis attributes

NEWS.md, R/RcppExports.R, man/gdal_formats.Rd, src/RcppExports.cpp, src/gdal_exp.cpp, src/gdalraster.h, tests/testthat/test-gdal_exp.R
`gdal_formats()` now returns a data frame with the supported raster and vector formats, and information about the capabilities of each format driver
=> gdal_formats(): return a data frame for raster and vector

src/geos_wkt.cpp
Fixes potential memory leak in `g_buffer()`: in src/geos_wkt.cpp, the geometry created with `OGR_G_Buffer()` was not deallocated with `OGR_G_DestroyGeometry()`.
=> deallocate the newly created geometry in _g_buffer()

R/gdalraster_proc.R, man/calc.Rd, tests/testthat/test-gdalraster_proc.R
This PR modifies `calc()`. Argument `usePixelLonLat` is deprecated as not necessary. Use of `pixelLon` / `pixelLat` in the calc expression is now auto-detected.
Also adds a small performance improvement by only computing `pixelY` if needed.
=> calc(): auto-detect use of pixelLon/pixelLat

R/RcppExports.R, src/RcppExports.cpp, src/geos_wkt.cpp, src/geos_wkt.h, tests/testthat/test-geos_wkt.R
Adds `_g_add_geom()`: add a geometry to a geometry container (operating on WKT). Currently `LINEARRING` (as `POLYGON`) to `POLYGON`, `POINT` to `MULTIPOINT`, `LINESTRING` to `MULTILINESTRING`, or `POLYGON` to `MULTIPOLYGON`.
Also adds support for `MULTIPOINT` in `_g_create()`.
=> add `_g_add_geom()`: add geom object to a container

DESCRIPTION, NEWS.md, src/gdalraster.cpp, src/gdalraster.h, tests/testthat/test-GDALRaster-class.R
Exposed in R but currently undocumented class method. Sets the filename on an object of class `GDALRaster` that has not had its filename previously set, i.e., `ds$getFilename() == ""` is `TRUE`. The filename cannot be set to `""`. Makes it possible to do:
```r
elev_file <- system.file("extdata/storml_elev.tif", package="gdalraster")
ds <- new(GDALRaster)
ds$setFilename(elev_file)
ds$open(TRUE)
ds$close()
```
Previously, the default constructor `GDALRaster::GDALRaster()` was only for allocating `std::vector<GDALRaster>`.
=> Add `GDALRaster::setFilename()`

DESCRIPTION, NEWS.md, R/RcppExports.R, R/gdal_rat.R, src/RcppExports.cpp, src/gdal_exp.cpp, src/gdalraster.h, tests/testthat/test-gdal_rat.R
Previously, a second `GDALRaster` object was instantiated internally from the passed object's filename, so open options on the passed object's dataset may not have been honored.
=> `buildRAT()`: if input is a `GDALRaster` object use it by reference

DESCRIPTION, NEWS.md, R/gdalraster.R, R/geom.R, man/GDALRaster-class.Rd, man/bbox_transform.Rd, man/g_transform.Rd, src/gdalraster.cpp, src/gdalraster.h
Adds `GDALRaster::getProjection()`, class method exposed to R. Equivalent to the existing `GDALRaster::getProjectionRef()`. 
Consistent with `osgeo.gdal.Dataset.getProjection()` / `osgeo.gdal.Dataset.getProjectionRef()` in the Python API:
https://gdal.org/api/python/raster_api.html#osgeo.gdal.Dataset.GetProjection
=> Add `GDALRaster::getProjection()`

DESCRIPTION, NEWS.md, R/gdalraster.R, man/GDALRaster-class.Rd, src/RcppExports.cpp, src/gdal_exp.cpp, src/gdalraster.cpp, src/gdalraster.h, tests/testthat/test-GDALRaster-class.R
Retrieve the actual block size for a given block offset.  Handles partial blocks at the edges of the raster and returns the true number of pixels. Exposes `GDALGetActualBlockSize()`.
=> Add `GDALRaster::getActualBlockSize()`

DESCRIPTION, R/display.R, R/gdalraster.R, R/gdalraster_proc.R, man/GDALRaster-class.Rd, man/read_ds.Rd, src/gdalraster.cpp, src/gdalraster.h, tests/testthat/test-GDALRaster-class.R
I'd like to be able to read and write Byte with R's raw vector type. This is unproblematic at the Rcpp level afaics. 
There are implications for the documentation and plotting (there's a failing plot test). 
I consider this a draft until those implications are discussed and dealt with. Thanks!   
The motivation is purely for the size of Byte vs Int32, for workflows that just move pixel data around. 
--------------------------------------------
Longer term motivation: 
It's not particularly  efficient to get raw vectors and then convert them to colours in R, but in time perhaps we can add helpers for that, i.e. I would also like to add a special r-only  type on input that bundles (1, or 3, or 4) raw vectors into Int32 with R's nativeRaster encoding i.e. …
=> add support for Byte<->raw IO

DESCRIPTION, NEWS.md, R/RcppExports.R, man/vsi_mkdir.Rd, man/vsi_rmdir.Rd, src/RcppExports.cpp, src/gdal_vsi.cpp, src/gdalraster.h, tests/testthat/test-gdal_vsi.R
Adds argument `recursive` in `vsi_rmdir()` and `vsi_mkdir()`. Supports deleting the directory and its content, or creating the directory and its ancestors, respectively.
This PR also fixes the `mode` argument in `vsi_mkdir()`. It was not passed correctly as an octal literal so file mode would be wrong. `mode` is now passed as a character string containing the file mode as octal.
=> Support recursive in `vsi_rmdir()` and `vsi_mkdir()` (also fixing `mode` in `vsi_mkdir()`)

DESCRIPTION, NEWS.md, R/gdalraster_proc.R, man/calc.Rd, tests/testthat/test-gdalraster_proc.R
#319 
`out_band` can be a vector of band numbers. Currently in that case, `expr` must return multiband output in a vector or matrix.
=> Support multiband output in `calc()`

DESCRIPTION, NEWS.md, src/gdal_exp.cpp, tests/testthat/test-gdal_exp.R
`ogrinfo()` checks for the argument `-json` in the character vector of arguments given in `cl_arg`. If present, it returns a JSON-formatted string.
This PR refactors the handling of `-json`, but also changes to the usual way of casting `Rcpp::Nullable` to the underlying type:
`Rcpp::CharacterVector cl_arg_in(cl_arg);`
This hopefully fixes:
`Error: ogrinfo() failed (could not create options struct)`
with GDAL 3.9.0beta1
=> Improve the check for `-json` as a possible `cl_arg` in `ogrinfo()`

src/gdal_exp.cpp
Undo version dependent arg passing to `GDALVectorInfo()` that was added in commit 13d5637. A workaround is no longer needed (and was ineffective anyway for the regression in 3.9.0beta1). See #324. Fixed in GDAL for 3.9.
=> ogrinfo(): revert to original arg passing in GDALVectorInfoOptions

DESCRIPTION, NEWS.md, R/gdal_helpers.R, R/gdalraster.R, man/GDALRaster-class.Rd, man/get_pixel_line.Rd, src/RcppExports.cpp, src/gdal_exp.cpp, src/gdalraster.cpp, src/gdalraster.h, tests/testthat/test-gdal_exp.R
Adds class method for alternate calling for `get_pixel_line()` on an object of class `GDALRaster`
also allows `xy` to be given as a two-column data frame that will be coerced to numeric matrix (originally required matrix input only)
=> add GDALRaster::get_pixel_line()

R/RcppExports.R, src/gdal_exp.cpp, src/rcpp_util.cpp, src/rcpp_util.h, tests/testthat/test-gdal_exp.R
The PR changes `_check_gdal_filename()` so that it uses R `path.expand()` for tilde expansion if needed, instead of `normalizePath()` previously. This avoids having a warning emitted when the filename being checked does not exists yet.
=> Use path.expand() instead of normalizePath() to avoid warning on Windows

R/vsifile.R, man/VSIFile-class.Rd, src/vsifile.cpp, src/vsifile.h, tests/testthat/test-VSIFile-class.R
This PR corrects `VSIFile::write()` so that the input must be given as `RawVector` instead of `RObject` for now. Support for other input data types could potentially be added later.
=> VSIFile::write(): input must be raw vector

DESCRIPTION, NEWS.md, R/vsifile.R, man/VSIFile-class.Rd, src/vsifile.cpp, src/vsifile.h, tests/testthat/test-VSIFile-class.R
This PR removes the `size` parameter from the `write()` method of `VSIFile`. It is unneeded since input can only be a `raw` vector and size of elements will always be 1. Document use of base R `readBin()` and `writeBin()` to read binary data from or write binary data to a raw vector.
=> VSIFile::write(): remove size param as unneeded

R/gdalraster.R, man/GDALRaster-class.Rd, src/gdalraster.cpp, src/gdalraster.h
This PR adds progress reporting in `GDALRaster::getDefaultRAT()`. Retrieving large raster attribute tables can take upward of ~20 seconds, e.g., a 66,468 row x 72 column table in a recent example case. Without a progress bar, it may appear that the method call is hung.
This PR also adds public field `quiet` on the class, set to `false` by default. It is not yet exported to R as a read/write field. The idea is provide a user setting on the object to control the amount of output from its methods, to be implemented later.
=> Add GDALProgressFunc in GDALRaster::getDefaultRAT()

R/RcppExports.R, man/vsi_copy_file.Rd, man/vsi_get_disk_free_space.Rd, man/vsi_mkdir.Rd, man/vsi_rename.Rd, man/vsi_rmdir.Rd, man/vsi_stat.Rd, man/vsi_sync.Rd, man/vsi_unlink.Rd, man/vsi_unlink_batch.Rd, src/RcppExports.cpp, src/gdal_vsi.cpp, src/gdalraster.h, tests/testthat/test-gdal_vsi.R
Several `vsi_*()` functions returned `0` or `-1` invisibly to indicate success/failure consistent with GDAL return values. This PR makes those return values visible to be consistent with return values from `VSIFile` class methods. Also makes `vsi_stat(filename, info = "size")` and `vsi_get_disk_free_space(path)` return as `bit64::integer64` type.
=> Make `vsi_*()` return values visible and use `integer64` type

DESCRIPTION, NEWS.md, R/gdalraster.R, man/GDALRaster-class.Rd, src/gdalraster.cpp, src/gdalraster.h, tests/testthat/test-GDALRaster-class.R
Adds new read/write fields in class `GDALRaster` exposed in R:  `infoOptions` and `quiet`.
Can be used to configure per-object settings (along with the existing field `readByteAsRaw`).
=> Add read/write fields `infoOptions` and `quiet` in class `GDALRaster`

DESCRIPTION, NEWS.md, R/ogr_manage.R
* The check for field name already exists was wrong.
* `srs` param was not passed to the internal create function.
=> Fixes in ogr_geom_field_create()

DESCRIPTION, NEWS.md, R/ogr_manage.R
Fixes `ogr_ds_create()`: `layer` name was not passed to the internal create function when `layer_defn` was used.
=> odg_ds_create(): fix layer name not passed with layer_defn

R/RcppExports.R, man/vsi_get_file_metadata.Rd, src/gdal_vsi.cpp
Add `print()` to display output of functions called within `if` block for GDAL >= 3.7.
=> Doc: update example for vsi_get_file_metadata()

inst/COPYRIGHTS, src/gdalraster.cpp, src/gdalraster.h
This PR changes the include in src/gdalraster.cpp from gdal_priv.h to gdal.h.
gdal_priv.h was included only for function `ARE_REAL_EQUAL`. Otherwise, that header is not needed because we are using the C API only. `ARE_REAL_EQUAL` was copied to src/gdalraster.h. This function is needed for recoding nodata values when raster data must be read as `double` (which includes `UInt32` raster data since R does not have an unsigned 32-bit integer data type).
=> Include gdal.h instead of gdal_priv.h and copy ARE_REAL_EQUAL from GDAL

src/vsifile.cpp, src/vsifile.h, tests/testthat/test-VSIFile-class.R
The finalizer function seems unneeded in this case.
=> Omit Rcpp .finalizer function in class VSIFile for now

DESCRIPTION, NEWS.md, R/gdalraster.R, man/GDALRaster-class.Rd, src/gdalraster.cpp, src/gdalraster.h
The default is to open datasets shared.
=> Add an alternate constructor in class GDALRaster to allow specifying shared = FALSE

DESCRIPTION, NEWS.md, R/gdalraster_proc.R, tests/testthat/test-gdalraster_proc.R
`var.names` must be in `expr`
Without this check, the input and output datasets would be left in an open condition after the error from `eval(calc_expr)`.
=> calc(): add input validation for variable names

DESCRIPTION, NEWS.md, R/ogr_manage.R, man/ogr_manage.Rd, tests/testthat/test-ogr_manage.R
Add param `overwrite` with default `FALSE` in `ogr_ds_create()` to avoid overwriting existing dataset (#400).
=> ogr_ds_create(): add param overwrite

tests/testthat/test-ogr_manage.R
resolves #409 
The test for GeoJSON layer did not need to check existence `with_update = TRUE`. The file being checked was in `inst/extdata`, which is read-only on the CRAN check servers for r-devel-linux-x86_64-debian. This fixes the test by removing `with_update = TRUE` from the initial check of the dataset in `inst/extdata`, then copying it to a temp file and checking `with_update = TRUE`.
=> Fix test in test-ogr_manage.R

NEWS.md, R/vsifile.R, man/VSIFile-class.Rd, src/vsifile.cpp, tests/testthat/test-VSIFile-class.R, vignettes/gdal-config-quick-ref.Rmd
This PR documents the `w+` access flag for class `VSIFile` and adds`CPL_VSIL_USE_TEMP_FILE_FOR_RANDOM_WRITE` configuration option in vignette "GDAL Config Quick Reference".
=> Document the w+ access flag for VSIFile

DESCRIPTION, NEWS.md, src/gdalraster.cpp
for better performance in the case of large attribute tables
=> Avoid data copy in GDALRaster::getDefaultRAT()

DESCRIPTION, NEWS.md, R/RcppExports.R, man/vsi_read_dir.Rd, src/RcppExports.cpp, src/gdal_vsi.cpp
Adds parameter `recursive`, `TRUE` to read the list of entries in the directory and subdirectories.
#425 
We use "recursive" for the parameter name here instead of "recurse" since we already have "recursive" in `vsi_mkdir()` and `vsi_rmdir()`.
Note that `max_files` is ignored when `recursive = TRUE`.
=> `vsi_read_dir()`: add parameter `recursive`

DESCRIPTION, NEWS.md, R/gdalraster.R, man/GDALRaster-class.Rd, src/gdalraster.cpp, src/gdalraster.h, tests/testthat/test-GDALRaster-class.R
clear the color table associated with a raster band (where supported by the driver)
=> add GDALRaster::clearColorTable()

R/display.R, R/gdalraster_proc.R, man/plot_raster.Rd, man/read_ds.Rd
This PR changes the default behavior for applying contrast enhancement. Previously, contrast enhancement by stretch to min/max per band was applied by default regardless of the input. The new behavior is documented as
>By default, contrast enhancement by stretch to min/max is applied when the input data are single-band grayscale with any raster data type, or three-band RGB with raster data type larger than Byte. The minimum/maximum of the input data are used by default (i.e., no outlier removal). No stretch is applied by default when the input is an RGB byte raster. These defaults can be overridden by specifying either the `minmax_def` argument (user-defined min/max per band), or the `minmax_pct_cut` argument (ignore outlier pixels based on a percentile range per band). These settings …
=> plot_raster(): default to no stretch when the input is an RGB Byte raster

R/gdalvector.R, man/GDALVector-class.Rd, src/gdalvector.cpp, src/gdalvector.h
#' Returns the attribute query string currently in use, or empty string (`""`)
#' if an attribute filter is not set.
=> add GDALVector::getAttributeFilter()

R/gdalvector.R, man/GDALVector-class.Rd, src/gdalvector.cpp, src/gdalvector.h
`$setSpatialFilter(wkt)`
#' Sets a new spatial filter from a geometry in WKT format. This method sets
#' the geometry to be used as a spatial filter when fetching features via the
#' `$getNextFeature()` or `$fetch()` methods. Only features that geometrically
#' intersect the filter geometry will be returned. Currently this test may be
#' inaccurately implemented (depending on the vector format driver), but it is
#' guaranteed that all features whose envelope overlaps the envelope of the
#' spatial filter will be returned. This can result in more shapes being
#' returned that should strictly be the case.
#' `wkt` is a character string containing a WKT geometry in the same coordinate
#' system as the layer. An empty string (`""`) may be passed indicating that
#' the current spatial filter …
=> Add GDALVector class methods setSpatialFilter() / getSpatialFilter()

DESCRIPTION, NEWS.md, R/gdalvector.R, R/ogr_manage.R, man/GDALVector-class.Rd, man/ogr_manage.Rd, src/gdalvector.cpp, src/gdalvector.h, src/ogr_util.cpp, tests/testthat/test-GDALVector-class.R
`$setIgnoredFields(fields)`
#' Set which fields can be omitted when retrieving features from the layer.
#' The `fields` argument is a character vector of field names.
#' If the format driver supports this functionality (testable using
#' `$testCapability()$IgnoreFields`), it will not fetch the specified fields
#' in subsequent calls to `$getFeature()` / `$getNextFeature()` / `$fetch()`,
#' and thus save some processing time and/or bandwidth. Besides field names of
#' the layer, the following special fields can be passed: `"OGR_GEOMETRY"` to
#' ignore geometry and `"OGR_STYLE"` to ignore layer style. By default, no
#' fields are ignored. Note that fields that are used in an attribute filter
#' should generally not be set as ignored fields, as most drivers (such as
#' those relying on the …
=> add `GDALVector::setIgnoredFields()`: set which fields can be omitted when retrieving features from the layer

DESCRIPTION, NEWS.md, R/gdalvector.R, man/GDALVector-class.Rd, src/gdalvector.cpp, src/gdalvector.h, tests/testthat/test-GDALVector-class.R
`$setNextByIndex(i)`
#' Moves the read cursor to the `i`th feature in the current result set
#' (with 0-based indexing).
#' This method allows positioning of a layer such that a call to
#' `$getNextFeature()` or `fetch()` will read the requested feature(s), where
#' `i` is an absolute index into the current result set. So, setting `i = 3`
#' would mean the next feature read with `$getNextFeature()` would have been
#' the 4th feature read if sequential reading took place from the beginning of
#' the layer, including accounting for spatial and attribute filters.
#' This method is not implemented efficiently by all vector format drivers. The
#' default implementation simply resets reading to the beginning and then calls
#' `GetNextFeature()` `i` times.
#' To determine if fast seeking is …
=> Add GDALVector::setNextByIndex()

DESCRIPTION, NEWS.md, R/gdalvector.R, man/GDALVector-class.Rd, src/gdalvector.cpp, src/gdalvector.h, tests/testthat/test-GDALVector-class.R
`$featureTemplate`
#' A list of the attribute and geometry field names, with `NA` values equivalent
#' to OGR NULL values. The list elements are fully typed with the corresponding
#' missing value types assigned (`NA_integer_`, `NA_real_`, `NA_character_`,
#' etc.). The `featureTemplate` is useful to initialize a new empty feature,
#' to which field and geometry values can be assigned, for use with the
#' `$createFeature()` method (create and write a new feature within the layer).
#' Note that geometry fields are initialized as `character` type in the
#' template, but may be set either to a `character` string specifying a
#' geometry in WKT format, or to a `raw` vector containing a geometry as WKB.
=> Add `featureTemplate` as a read-only field in class `GDALVector`

DESCRIPTION, NEWS.md, R/gdalvector.R, man/GDALVector-class.Rd, src/gdalvector.cpp, src/gdalvector.h, tests/testthat/test-GDALVector-class.R
`$deleteFeature(fid)`
#' Delete feature from layer. The feature with the indicated feature ID is
#' deleted from the layer if supported by the format driver. The value of `fid`
#' must be a numeric scalar, optionally carrying the `bit64::integer64` class
#' attribute (should be a whole number, will be truncated). The `DeleteFeature`
#' element in the list returned by `$testCapability()` can be checked to
#' establish if this layer has delete feature capability. Returns logical
#' `TRUE` if the operation succeeds, or `FALSE` on failure.
=> Add `GDALVector::deleteFeature()`

src/gdalraster.cpp, tests/testthat/test-GDALRaster-class.R
require that the input is a finite value, to avoid setting NA, NaN, Inf
=> Handle NA when attempting to set nodata value, scale and offset

DESCRIPTION, NEWS.md, R/gdalraster.R, man/GDALRaster-class.Rd, src/gdalraster.cpp, src/gdalraster.h, tests/testthat/test-GDALRaster-class.R
Set dataset or band-level metadata from a character vector of NAME=VALUE pairs (instead of per metadata item with the existing `$setMetadataItem()`).
=> Add GDALRaster::setMetadata()

tests/testthat/test-GDALRaster-class.R
Also, dataset metadata would not persist in GTiff unless `GDALSetMetadata()` was done after setting the projection and geotransform. Possibly related to https://github.com/OSGeo/gdal/issues/6015.
=> Test: use `create()` with `return_obj` argument in tests of get/set metadata

DESCRIPTION, NEWS.md, src/gdal_exp.cpp
Previously only tested for GDAL_DCAP_CREATECOPY.  For CreateCopy(), need to test also for GDAL_DCAP_CREATE:
>GDAL_DCAP_CREATECOPY
Capability set by a driver that implements the CreateCopy() API.
>If GDAL_DCAP_CREATECOPY is not defined, but GDAL_DCAP_CREATE is set, a generic CreateCopy() implementation is available and will use the Create() API of the driver. So to test if some CreateCopy() implementation is available, generic or specialize, test for both GDAL_DCAP_CREATE and GDAL_DCAP_CREATECOPY.
=> createCopy(): test driver for GDAL_DCAP_CREATECOPY or GDAL_DCAP_CREATE

.github/workflows/R-CMD-check.yaml, .github/workflows/pkgdown.yaml, .github/workflows/rhub.yaml, .github/workflows/scorecard.yml, .github/workflows/test-coverage.yaml
This pull request is created by [StepSecurity](https://app.stepsecurity.io/securerepo) at the request of @ctoney. Please merge the Pull Request to incorporate the requested changes. Please tag @ctoney on your message if you have any questions related to the PR.
The GITHUB_TOKEN is an automatically generated secret to make authenticated calls to the GitHub API. GitHub recommends setting minimum token permissions for the GITHUB_TOKEN.
- [GitHub Security Guide](https://docs.github.com/en/actions/security-guides/automatic-token-authentication#using-the-github_token-in-a-workflow)
- [The Open Source Security Foundation (OpenSSF) Security Guide](https://github.com/ossf/scorecard/blob/main/docs/checks.md#token-permissions)
GitHub Action tags and Docker tags are mutable. This poses a security …
=> [StepSecurity] ci: Harden GitHub Actions

CONTRIBUTING.md
[Cpplint](https://github.com/cpplint/cpplint) is in use in the development environment for C++ code style checking. A [VSCode plugin](https://marketplace.visualstudio.com/items?itemName=mine.cpplint) is available.
=> Doc: add cpplint in dev practices

DESCRIPTION, NEWS.md, R/RcppExports.R, R/ogr_manage.R, man/ogr_manage.Rd, src/RcppExports.cpp, src/gdalvector.cpp, src/ogr_util.cpp, src/ogr_util.h, tests/testthat/test-ogr_manage.R
#' `ogr_layer_rename()` renames a layer in a vector dataset. This operation is
#' implemented only by layers that expose the `Rename` capability (see
#' `ogr_layer_test_cap()` above). This operation will fail if a layer with the
#' new name already exists. Returns a logical scalar, `TRUE` indicating success.
#' Requires GDAL >= 3.5.
=> Add `ogr_layer_rename()`: rename an existing layer in a vector dataset

DESCRIPTION, NEWS.md, R/ogr_define.R
if `srs` is `NULL` set to empty string, avoids exception in `ogr_layer_create()` if no SRS is given when using a layer definition created with `ogr_def_layer()`
=> ogr_def_geom_field(): fix input validation for the srs argument

DESCRIPTION, NEWS.md, R/gdalvector.R, man/GDALVector-class.Rd, src/gdalvector.cpp, src/gdalvector.h, src/rcpp_util.h, tests/testthat/test-GDALVector-class.R
Methods for writing a new feature or updating an existing feature in a vector layer.
`$setFeature(feature)`
Rewrites/replaces an existing feature. This method writes a feature based on
the feature id within the input feature. The `feature` argument is a named
list of fields and their values, and must include a `$FID` element
referencing the existing feature to rewrite. The `RandomWrite` element in
the list returned by `$testCapability()` can be checked to establish if this
layer supports random access writing via `$setFeature()`.
The way omitted fields in the passed `feature` are processed is driver
dependent:
* SQL-based drivers which implement set feature through SQL UPDATE will skip
unset fields, and thus the content of the existing feature will be
preserved.
* The shapefile driver …
=> `GDALVector`: add class methods for writing features in a layer: `$createFeature()`, `$setFeature()`, `$upsertFeature()`

DESCRIPTION, NEWS.md, R/gdalvector.R, man/GDALVector-class.Rd, src/gdalvector.cpp, tests/testthat/test-GDALVector-class.R
`$returnGeomAs`
#' Character string specifying the return format of feature geometries.
#' Must be one of `WKT`, `WKT_ISO`, `WKB` (the default), `WKB_ISO`,
#' `SUMMARY` (GDAL >= 3.7), `TYPE_NAME` or `NONE`. Using `WKB`/`WKT` exports as
#' 99-402 extended dimension (Z) types for Point, LineString, Polygon,
#' MultiPoint, MultiLineString, MultiPolygon and GeometryCollection. For other
#' geometry types, it is equivalent to using `WKB_ISO`/`WKT_ISO` (see
#' \url{https://libgeos.org/specifications/wkb/}).
for example with summary:
```r
lyr$returnGeomAs <- "SUMMARY"
lyr$getNextFeature()
#> $FID
#> integer64
#> [1] 1
#> 
#> $Event_ID
#> [1] "MO3742409133620170304"
#> 
#> $Map_ID
#> integer64
#> [1] 10011338
#> 
#> $Ig_Date
#> [1] "2017-03-04"
#> 
#> $geometry
#> [1] "MULTIPOLYGON : 2 …
```
=> `GDALVector`: add `SUMMARY` option for the per-object setting `$returnGeomAs`

DESCRIPTION, NEWS.md, R/gdalvector.R, man/GDALVector-class.Rd, src/gdalvector.cpp, src/gdalvector.h, tests/testthat/test-GDALVector-class.R
GDAL API provides only `OGRLayer::SetIgnoredFields()` for reasons given in RFC 29.
`GDALVector::setSelectedFields()` sets the fields to include. Other than the specified fields will be ignored. This mimics the behavior of the `-select` argument in the `ogr2ogr` command line utility.
`$setSelectedFields(fields)`
#' Set which fields will be included when retrieving features from the layer.
#' The `fields` argument is a character vector of field names. Passing an
#' empty string (`""`) for `fields` will reset to no ignored fields.
#' See the `$setIgnoredFields()` method above for more information. The data
#' source must provide IgnoreFields capability in order to set selected
#' fields. Note that geometry fields, if desired, must be specified when setting
#' selected fields, either by …
=> `GDALVector`: add method `$setSelectedFields()`, alternative to `$setIgnoredFields()`

DESCRIPTION, NEWS.md, R/gdal_create.R, R/gdalraster_proc.R, R/ogr_define.R, R/ogr_manage.R, man/create.Rd, man/createCopy.Rd, man/ogr_define.Rd, man/ogr_manage.Rd, src/RcppExports.cpp, src/gdalraster_types.h, src/gdalvector.cpp, src/gdalvector.h, src/ogr_util.cpp, src/ogr_util.h, tests/testthat/test-GDALVector-class.R, tests/testthat/test-ogr_manage.R
`TRUE` to return a writable `GDALVector` object on the created layer.
Done previously for raster in #464.
=> Add `return_obj` argument in `ogr_ds_create()` and `ogr_layer_create()`

DESCRIPTION, NEWS.md, R/RcppExports.R, R/ogr_define.R, R/ogr_manage.R, man/ogr_define.Rd, man/ogr_manage.Rd, src/RcppExports.cpp, src/gdalvector.cpp, src/ogr_util.cpp, src/ogr_util.h, tests/testthat/test-ogr_manage.R, vignettes/articles/gdalvector-draft.Rmd
potentially breaking change but assumed to be unused in feature class / field creation
=> Remove `is_ignored` from feature class definition

DESCRIPTION, NEWS.md, src/gdalvector.cpp
We already iterate each element of the data frame in `GDALVector::fetch()`, so set `NA` values there and skip initialization when the vectors are created. Potential performance improvement when reading large result sets.
=> `GDALVector::initDF_()`: create the data frame vectors with `Rcpp::no_init()`

DESCRIPTION, NEWS.md, R/gdalvector.R, man/GDALVector-class.Rd, src/gdalvector.cpp, src/gdalvector.h, src/ogr_util.cpp, tests/testthat/test-GDALVector-class.R, vignettes/articles/gdalvector-draft.Rmd
`GDALVector::featureTemplate` was exposed to R as a read-only field, containing a list object meant to be a template for a feature in the layer with field values initialized to `NA`.  It turned out not to be very helpful for its intended purpose. It is redundant with simply reading a feature from the layer and examining its structure (with `str()`), or examining the structure of the feature class definition returned by the method `getLayerDefn()`. Also, the class method `fetch()` can be called with `n = 0` to return a 0-row data frame that is fully typed.
The internal class method `setFeatureTemplate_()`, called in the constructor, assumed that the data frame returned by `initDF_()` was initialized to `NA` values. PR #516 changed the data frame creation to use `Rcpp::no_init()` for …
=> `GDALVector`: remove the exposed field `$featureTemplate` as not needed / not useful (and fixing Valgrind errors)

DESCRIPTION, NEWS.md, src/gdalvector.cpp, tests/testthat/test-GDALVector-class.R
Fixes eventual segfault. This PR also adds new tests for class `GDALVector`.
=> Fix `GDALVector::setSpatialFilter()`: SRS was not set on the geometry before using it as the layer spatial filter

DESCRIPTION, NEWS.md, src/geom_api.cpp
=> g_make_valid(): destroy the input geometry object before return if OGR MakeValid() returns NULL

src/gdalvector.cpp, tests/testthat/test-GDALVector-class.R
On the R side, `NA`, `NULL` and empty vector like `raw(0)` map to OGR NULL (i.e., `SetFieldNull()` for attribute fields, or `SetGeomField()` to NULL geometry). This PR mainly improves input checking for `NA`/`NULL` and adds several tests.
=> GDALVector: improve NULL handling for attribute and geometry fields in feature write methods

DESCRIPTION, NEWS.md, R/RcppExports.R, man/vsi_read_dir.Rd, src/RcppExports.cpp, src/gdal_vsi.cpp, src/gdal_vsi.h
Omit `"."` and `".."` from the listing.
Add argument `all_files`, `TRUE` to include hidden files.
Sort the listing alphabetically.
Omitting `"."` and `".."` is a behavior change.
=> `vsi_read_dir()`: omit `"."` and `".."` and sort the returned listing, add arg `all_files`

DESCRIPTION, NEWS.md, R/ogr_manage.R, man/ogr_manage.Rd, src/ogr_util.cpp, tests/testthat/test-ogr_manage.R
the `layer` argument may be `NULL` or empty string in certain `ogr_manage` functions, defaulting to the first layer by index (mainly convenience for single-layer formats)
=> Support `NULL` layer argument for certain `ogr_manage` functions

tests/testthat/test-VSIFile-class.R
Previously we had a test that created a file with:
```r
vf <- new(VSIFile, mem_file, "w")
```
and after writing data, also tested subsequent reads under the same file handle/access. This worked without error on GDAL <= 3.8.4 and probably later (e.g., 3.9.0?), but the subsequent read does not work under GDAL 3.10.0dev-892f3ecc8d3c6b99004c1575f49fc04ddee9b90a, released 2024/10/13. This PR fixes the test by changing to:
```r
vf <- new(VSIFile, mem_file, "w+")
```
This seems like correct behavior, but also seems to be a behavior change somewhere between GDAL 3.8.4 and 3.10dev.
=> Fix test for VSIFile: open with w+ to create file for read/write

DESCRIPTION, NEWS.md, src/gdalvector.cpp
`RcppInt64::wrap()` uses `std::memcpy()`. If the input vector has size 0, clang-asan reports something like (e.g., in https://github.com/USDAForestService/gdalraster/actions/runs/12849059469):
```
> ## NULL when no more features are available
> lyr$getNextFeature()
/github/home/R/x86_64-pc-linux-gnu-library/4.5/RcppInt64/include/rcppint64_bits/as_wrap.h:102:32: runtime error: null pointer passed as argument 2, which is declared to never be null
/usr/include/string.h:44:28: note: nonnull attribute specified here
#0 0x7f2e9e5efa44 in SEXPREC* Rcpp::wrap<std::__1::vector<long, std::__1::allocator<long>>>(std::__1::vector<long, std::__1::allocator<long>> const&) /github/home/R/x86_64-pc-linux-gnu-library/4.5/RcppInt64/include/rcppint64_bits/as_wrap.h:102:9
#1 0x7f2e9e6987ed in …
```
=> `GDALVector::createDF_()`: avoid clang-asan undefined-behavior error

tests/testthat/test-GDALVector-class.R
fixes #575 (don't call `bit64::is.na.integer64` directly)
=> Remove direct call to an S3 method in the GDALVector tests

R/RcppExports.R, R/gdal_helpers.R, man/apply_geotransform.Rd, man/get_pixel_line.Rd, man/inv_project.Rd, man/transform_xy.Rd, src/gdal_exp.cpp, src/rcpp_util.cpp, src/rcpp_util.h, src/transform.cpp, tests/testthat/test-gdal_exp.R, tests/testthat/test-gdal_helpers.R, tests/testthat/test-transform.R
In `transform_xy()`, `inverse_proj()`, `apply_geotransform()`, `get_pixel_line()`
=> Accept one (x, y) as a vector in functions that expect matrix or data frame xy

src/gdalvector.cpp, tests/testthat/test-GDALVector-class.R
=> GDALVector: set the member variable m_layer_name when opening a default layer first by index

R/RcppExports.R, R/gdal_helpers.R, man/inv_project.Rd, man/transform_xy.Rd, src/gdal_exp.cpp, src/rcpp_util.cpp, src/transform.cpp, tests/testthat/test-gdal_exp.R, tests/testthat/test-transform.R
fixes #587 
In the case of `transform_xy()` and `inv_project()`, related to the issue described in https://github.com/OSGeo/gdal/issues/11817 and accounts for future behavior change in https://github.com/OSGeo/gdal/pull/11819.
=> Handle NA in the input coordinates to transform_xy(), inv_project(), transform_bounds(), apply_geotransform() and get_pixel_line()

src/vsifile.cpp
since `VSIFille::close()` has a return value
=> Class VSIFille: call VSIFCloseL() in the destructor instead of class method close()

src/gdalvector.cpp
This doesn't really have user facing implications, but the default constructor might be needed e.g. to allocate `std::vector<GDALVector>`. In case a user did instantiate in R with `lyr <- new(GDALVector)` then the object should be well behaved.
=> GDALVector: initialize the default constructor

R/gdalraster_proc.R, man/read_ds.Rd
Pre-allocates the output vector based on the size of the unioned data type across all bands (no effect if `as_list = TRUE`). Avoids data copies that would result from appending to the vector repeatedly for multi-band output as done previously.
In addition,
* adds input validation
* ~~`readByteAsRaw` is only set if the unioned data type across all bands is Byte~~
* avoid calculating the corner coordinates twice for the bbox attribute
* minor edits in the documentation
Edit: allow `as_raw = TRUE` to result in setting `readByteAsRaw` on the dataset, even if the unioned data type across all bands being read is not Byte (with the warning). It's possible with `as_list = TRUE`, and a multi-band raster with mixed data types, that a user could want the Byte bands as `raw`, although this is …
=> read_ds(): pre-allocate the output vector and other improvements

R/gdalvector.R, man/GDALVector-class.Rd, src/gdalvector.cpp, tests/testthat/test-GDALVector-class.R
=> enable full info() on vector-via-sql

src/gdal_exp.cpp, src/gdalraster.cpp, src/gdalraster.h, tests/testthat/test-GDALRaster-class.R
closes #613 
The return value of `GDALRaster::getRasterXSize()` / `GDALRaster::getRasterYSize()` was previously `int`, only because the underlying API calls to `GDALGetRasterXSize(()` / `GDALGetRasterYSize()` return `int`. And then `GDALRaster::dim()` returned `std::vector<int>` so when it gets back to R it has `storage.mode` of `integer` and R tries to do an integer operation as documented
`?Arithmetic`
>If either argument is complex the result will be complex, otherwise if one or both arguments are numeric, the result will be numeric.  If both arguments are of type integer, the type of the result of ‘/’ and ‘^’ is numeric and for the other operators it is integer (with overflow, which occurs at +/- (2^31 - 1), returned as ‘NA_integer_’ with a warning).
The PR mainly changes the return …
=> Fix potential integer overflow when multiplying raster dimensions in R without explicit as.numeric()

src/gdalvector.cpp, tests/testthat/test-GDALVector-class.R
avoids test failure if GDAL < 3.7, and still prints some minimal info when `ogrinfo()` is unavailable via API on GDAL < 3.7
=> GDALVector::info(): maintain fallback giving minimal info if GDAL < 3.7

R/RcppExports.R, R/ogr_manage.R, src/RcppExports.cpp, src/gdalvector.cpp, src/gdalvector.h, src/ogr_util.cpp, src/ogr_util.h
allocate on the heap and return a pointer (internal C++ functions `create_ogr()` and `ogr_layer_create()` registered as object factories via `RCPP_MODULE(mod_GDALVector)`)
C++ functions that accept `GDALVector` objects now use pass by const reference (`GDALVector* const&` )
adds explicit `GDALVector::~GDALVector()`, releasing the underlying dataset if needed
=> Implement ogr_ds_create() and ogr_layer_create() as GDALVector object factories

R/gdalvector.R, man/GDALVector-class.Rd, src/gdalvector.cpp
Use the GDAL default which will be `GEOMETRY_METADATA_ENCODING=OGC` if not specified.
More built-in support for geoarrow should be added in the future, but users can also set the metadata encoding to `GEOARROW` if desired.
=> GDALVector::getArrowStream(): default to OGC metadata encoding

R/gdalvector.R, man/GDALVector-class.Rd, src/gdalvector.cpp
GDAL >= 3.6
Also adds to the `GDALVector` class documentation for the `$getArrowStream()` method:
>See also the `$testCapability()` method above to check whether the format
driver provides a specialized implementation (`FastGetArrowStream`), as
opposed to the (slower) default implementation. Note however that
specialized implementations may fallback to the default when attribute or
spatlal filters are in use.
(See the GDAL documentation for [`OGR_L_GetArrowStream()`](https://gdal.org/en/stable/api/vector_c_api.html#_CPPv420OGR_L_GetArrowStream9OGRLayerHP16ArrowArrayStreamPPc).)
=> `GDALVector::testCapability()`: add `FastGetArrowStream` and `FastWriteArrowBatch` in the returned list of layer capabilities

R/gdalvector.R, man/GDALVector-class.Rd, src/gdalvector.cpp, src/gdalvector.h, tests/testthat/test-GDALVector-class.R
Also refactors the internal class method `GDALVector::OGRFeatureFromList_()`, separating out much of the initial input validation into `GDALVector::validateFeatInput_()`.
>`$batchCreateFeature(feature_set)`
Batch version of `$createFeature()`. Creates and writes a batch of new
features within the layer from input passed as a data frame in the
`feature_set` argument. Column names in the data frame must match field
names of the layer and have compatible data types. The specifications
listed above under the `$fetch()` method generally apply to input data
types for writing, but integers may be passed as 'numeric', and
the 'integer64' class attribute is not strictly required on 'numeric'
input if it is not needed for the data being passed to an OFTInteger64
field.
Returns a logical vector of …
=> Add `GDALVector::batchCreateFeature()`: write a batch of features to a layer from data frame input 

R/gdalvector.R, man/GDALVector-class.Rd, src/gdalvector.cpp, src/gdalvector.h, tests/testthat/test-GDALVector-class.R
So that the `force` argument to `GDALVector::startTransaction()` can be removed, and the default of `FALSE` supports the typical use cases anyway. The user can now set, e.g., `lyr$transactionsForce <- TRUE`, on a per-object basis to enable emulated transactions to be attempted.
(A limitation of `RCPP_EXPOSED_CLASS` is that we cannot supply default argument values in class methods, so using writable fields on the object is generally a decent workaround for setting various options.)
>`$transactionsForce`
A logical value, `FALSE` by default. Affects the behavior of attempted
transactions on the layer (see the `$startTransaction()` method below).
By default, only "efficient" transactions will be attempted. Some drivers
may offer an emulation of transactions, but sometimes with significant …
=> Add the writable field `GDALVector::transactionsForce`, defaulted to `FALSE`

src/cmb_table.h, src/gdalraster.h, src/gdalvector.h, src/running_stats.h, src/vsifile.h
Adds inline `// cppcheck-suppress unknownMacro` comment lines above calls to `RCPP_EXPOSED_CLASS()` to avoid triggering `error: There is an unknown macro here somewhere. Configuration is required.`
Requires using the `--inline-suppr` command-line argument. Something like the following tends to give useful information from cppcheck on the gdalraster src directory:
```
cppcheck -I /usr/share/R/include -I /usr/include/gdal -i src/RcppExports.cpp --enable=style --error-exitcode=1 --inline-suppr src
```
=> Add inline `// cppcheck-suppress unknownMacro` on calls to `RCPP_EXPOSED_CLASS()`

src/gdalvector.cpp, src/geom_api.cpp, src/geom_api.h, tests/testthat/test-GDALVector-class.R
=> Account for possible `convertToLinear` and/or `promoteToMulti` in the GIS attributes attached to vector read outputs

tests/testthat/test-GDALVector-class.R
This test would fail if GDAL was built without libspatialite support. This seems to be the case on the macos platforms on r-universe?
=> Fix a unit test for `GDALVector::info()`: condition on `has_spatialite()`

R/gdalvector.R, man/GDALVector-class.Rd
The full class documentation will undergo further editing, but this PR removes the note re: "currently under development... supporting read access", as it is now basically feature complete relative to the initial release target.
@title Class encapsulating a vector layer in a GDAL dataset
@description
`GDALVector` provides an interface for accessing a vector layer in a GDAL
dataset and calling methods on the underlying `OGRLayer` object.
An object of class `GDALVector` persists an open connection to the dataset,
and exposes methods that retrieve layer information, set attribute and
spatial filters, read feature data via traversal by traditional row-based
cursor including a direct analog of `DBI::dbFetch()`, read via
column-oriented Arrow Array stream, write new features in a layer, …
=> Doc: update GDALVector class description

R/geom.R, man/g_factory.Rd, src/geom_api.cpp, tests/testthat/test-geom.R
Only an empty GeometryCollection can be created with `g_create()`, which can then be used as a container with `g_add_geom()`.
=> Geom: support GeometryCollection in `g_create()`

R/cmb_table.R, R/gdalraster.R, R/gdalvector.R, R/geom.R, R/running_stats.R, R/vsifile.R, man/CmbTable-class.Rd, man/GDALRaster-class.Rd, man/GDALVector-class.Rd, man/RunningStats-class.Rd, man/VSIFile-class.Rd, man/g_factory.Rd
Restructures so that some information is moved up from the constructor return value section into the main class description section. Mainly to emphasize that named arguments are not supported in the C++ class methods, i.e., the Rcpp exposed classes are pretty close to C++ so document that behavior more emphatically, e.g.,
>`GDALRaster` is a C++ class exposed directly to R (via `RCPP_EXPOSED_CLASS`). Fields and methods of the class are accessed using the `$` operator. **Note that all arguments to class methods are required and must be given in the order documented.** Naming the arguments is optional but may be preferred for readability.
Partially addresses #648.
=> Doc: update descriptions for the C++ exposed classes and emphasize lack of named argument support

R/ogr_proc.R, man/ogr_proc.Rd
To be consistent with other functions that optionally return a `GDALVector` or `GDALRaster` object.
`ogr_proc()` is not in a release version yet so not designated as a breaking change.
=> `ogr_proc()`: rename argument `return_lyr_obj` to `return_obj`

R/display.R
Avoids possible:
```r
#> Warning in r[i_begin:i_end] <- ds$read(b, xoff, yoff, xsize, ysize, out_xsize,
#> : number of items to replace is not a multiple of replacement length
```
in case the input dimensions for reading the raster were calculated, e.g., given to `plot_raster()` as something like `xsize = dm[1] / 2`, and we get a fractional value. Coerce to whole number by truncation.
=> `plot_raster()`: ensure `out_xsize` / `out_ysize` are whole numbers in the internal call to `read_ds()`

R/RcppExports.R, R/gdalraster_proc.R, man/rasterize.Rd, src/RcppExports.cpp, src/gdal_exp.cpp, src/gdalraster.h, tests/testthat/test-gdalraster_proc.R
`rasterize()` previously supported only creation of a new raster dataset for the output. This PR adds support for passing an object of class `GDALRaster` for an existing dataset to be used as the output target, in which case the affected pixels are updated in-place.
>@param `dstfile` Either a character string giving the filename of the
output raster dataset, or an object of class `GDALRaster` for the output.
Must support update mode access. If given as a filename, this file will
be created (or overwritten if it already exists - see Note).
If given as a `GDALRaster` object for an existing dataset, then the affected
pixels are updated in-place (object must be open with write access).
=> `rasterize()`: support passing a `GDALRaster` object for in-place updating

R/gdal_helpers.R, man/getCreationOptions.Rd, tests/testthat/test-gdal_helpers.R
This was implemented as proposed in https://github.com/USDAForestService/gdalraster/discussions/649. Lacking additional feedback, it was assumed that the new return value is satisfactory. Otherwise, glad to make other changes as needed.
Once the PR is merged, the updated documentation will be available at:
https://usdaforestservice.github.io/gdalraster/reference/getCreationOptions.html
=> getCreationOptions(): change the return value to a named list of options with their information

R/gdal_helpers.R, man/getCreationOptions.Rd
accounts for https://github.com/OSGeo/gdal/issues/11967
originally motivated by discussion in #649
=> getCreationOptions(): include min/max attributes in the returned list if GDAL >= 3.11

R/RcppExports.R, R/gdalraster.R, man/GDALRaster-class.Rd, src/RcppExports.cpp, src/gdal_exp.cpp, src/gdalraster.cpp, src/gdalraster.h, tests/testthat/test-GDALRaster-class.R
`$get_block_indexing(band)`
Helper method returning a numeric matrix with named columns: `xblockoff`,
`yblockoff`, `xoff`, `yoff`, `xsize`, `ysize`, `xmin`, `xmax`, `ymin`,
`ymax`. For the meanings of these names, refer to the following class
methods below: `$getBlockSize()`, `$getActualBlockSize` and `$read()`.
All offsets are zero-based. The columns `xmin`, `xmax`, `ymin` and
`ymax` give the extent of each block in geospatial coordinates.
This method provides indexing values for the block layout of the given
`band` number. The returned matrix has number of rows equal to the number
of blocks comprising the band, with blocks ordered left to right, top
to bottom. The `xoff`/`yoff` values are pixel offsets to the start of a
block. The `xsize`/`ysize` values give the actual block sizes …
=> Add `GDALRaster::get_block_indexing()`: helper method to get indexing values for the block layout

R/RcppExports.R, src/gdal_exp.cpp, src/gdalraster.cpp
use the internal helper function `bbox_grid_to_geo_()` added in #667
=> GDALRaster::bbox(): minor refactor to use bbox_grid_to_geo_()

R/RcppExports.R, R/geom.R, man/g_measures.Rd, man/g_transform.Rd, src/RcppExports.cpp, src/geom_api.cpp, src/geom_api.h, tests/testthat/test-geom.R
`g_geodesic_area()` computes geometry area, considered as a surface on the
underlying ellipsoid of the SRS attached to the geometry. The returned area
will always be in square meters, and assumes that polygon edges describe
geodesic lines on the ellipsoid. If the geometry SRS is not a geographic
one, geometries are reprojected to the underlying geographic SRS.
By default, input geometry vertices are assumed to be in longitude/latitude
order if using a geographic coordinate system. This can be overridden with
the `traditional_gis_order` argument. Returns the area in square meters, or
`NA` in case of error (unsupported geometry type, no SRS attached, etc.)
Requires GDAL >= 3.9.
`g_geodesic_length()` computes the length of the curve, considered as a
geodesic line on the underlying ellipsoid …
=> Geom API: add `g_geodesic_area()` and `g_geodesic_length()`

R/RcppExports.R, R/geom.R, man/g_binary_op.Rd, man/g_binary_pred.Rd, man/g_buffer.Rd, man/g_envelope.Rd, man/g_factory.Rd, man/g_make_valid.Rd, man/g_measures.Rd, man/g_query.Rd, man/g_transform.Rd, man/g_wk2wk.Rd, src/RcppExports.cpp, src/geom_api.cpp, src/geom_api.h, tests/testthat/test-geom.R
To support authority compliant order for geometries using geographic coordinates.
@param `traditional_gis_order` Logical value, `TRUE` to use traditional GIS
order of axis mapping (the default) or `FALSE` to use authority compliant
axis order. By default, input `geom` vertices are assumed to
be in longitude/latitude order if `srs_from` is a geographic coordinate
system. This can be overridden by setting `traditional_gis_order = FALSE`.
=> g_transform(): add argument traditional_gis_order

R/gdalvector.R, man/GDALVector-class.Rd, src/gdalvector.cpp, src/gdalvector.h, tests/testthat/test-GDALVector-class.R
`$getIgnoredFields()`
Returns a character vector containing the list of currently ignored fields,
or an empty vector (`character(0)`) if no fields are currently set to
ignored (or if the format driver does not support ignored fields).
=> Add GDALVector::getIgnoredFields()

R/RcppExports.R, R/geom.R, man/bbox_transform.Rd, man/transform_bounds.Rd, src/transform.cpp
Update to be consistent with the GDAL documentation change in https://github.com/OSGeo/gdal/commit/1a3f781304cd2856ec0438b2f773357907d7d893 clarifying that the output values, not input values, need to be checked in cases that cross the antimeridian.
https://lists.osgeo.org/pipermail/gdal-dev/2025-April/060416.html
=> Doc: update for transform_bounds() consistent with upstream documentation change

inst/extdata/doctype.xml, src/gdalraster.cpp, src/gdalvector.cpp, tests/testthat/test-GDALRaster-class.R, tests/testthat/test-GDALVector-class.R
Mainly adds the `GDAL_OF_VERBOSE_ERROR` open flag for `GDALOpenEx()` to give more informative feedback if a class constructor fails to open a dataset (in `GDALRaster` and `GDALVector`).
Adds the file inst/extdata/doctype.xml, copied from GDAL autotest, which is used there in some cases to test "not recognized as being in a supported file format".
=> Add more error messages from GDAL in a few places

src/gdalraster.cpp, tests/testthat/test-GDALRaster-class.R, tests/testthat/test-gdalraster_proc.R
Allow geospatial coordinates that are exactly on the right or bottom edges of the raster to be considered as inside when doing single-pixel extract (i.e., nearest neighbor).
Match behavior in https://github.com/OSGeo/gdal/pull/12087.
=> Fix `GDALRaster::pixel_extract()` for points exactly on the right or bottom edges of the raster

R/RcppExports.R, man/get_cache_used.Rd, src/RcppExports.cpp, src/gdal_exp.cpp, src/gdalraster.h, tests/testthat/test-gdal_exp.R
Previously this function returned an integer value in MB. This PR adds the argument `units` with default of MB, adding the option to return in bytes, KB or GB. The return value is now int64 (R numeric type carrying the integer64 class attribute).
> Get the size of memory in use by the GDAL block cache
>
> `get_cache_used()` returns the amount of memory currently in use for
> GDAL block caching. Wrapper of `GDALGetCacheUsed64()` with return
> value in MB by default.
> 
> @param units Character string specifying units for the return value. One of
> `"MB"` (the default), `"GB"`, `"KB"` or `"bytes"` (values of `"byte"`,
> `"B"` and empty string `""` are also recognized to mean bytes).
> @returns Numeric value carrying the `integer64` class attribute. Amount of
> cache memory in use in the …
=> `get_cache_used()`: change return value to R numeric carrying the integer64 class attribute and add argument `units`

R/gdalvector.R, man/GDALVector-class.Rd
Add missing option in the list:
* MAX_FEATURES_IN_BATCH=integer. Maximum number of features to retrieve in an ArrowArray batch. Defaults to 65536.
=> Doc: add missing option in `GDALVector::arrowStreamOptions`

.github/workflows/R-CMD-check.yaml, DESCRIPTION, README.Rmd, README.md, configure, configure.ac, src/Makevars.win
External PROJ is not needed since gdalraster now requires GDAL >= 3.1. PROJ has been a GDAL build requirement since 3.0, and gdalraster only uses PROJ via GDAL headers (i.e., we use GDAL's libinternalproj). This PR removes configuration of the PROJ include directory and libs in configure.ac. Optional local copies of the GDAL and PROJ data directories are still supported. PROJ availability to GDAL at runtime is also still tested in configure, but link testing is removed. The DESCRIPTION file removes PROJ as a separate dependency in the SystemRequirements list (and also removes libxml2 since it is  only an indirect system requirement for the imported package xml2). The README file is updated to remove references to external PROJ as a dependency.
=> configure: remove configuration of PROJ include directory and libs

vignettes/vector-api-overview.Rmd
Still considered draft, but once merged the web version will be rendered at:
https://usdaforestservice.github.io/gdalraster/articles/vector-api-overview.html
Review, comments and suggestions are welcome and much appreciated.
=> Add "Vector API Overview" as a package vignette [DRAFT]

R/gdal_helpers.R, R/gdal_util.R
Doing checks of the form:
```r
ds <- try(new(GDALRaster, filename_in), silent = TRUE)
if (is(ds, "Rcpp_GDALRaster"))
```
are now wrapped with
```r
push_error_handler("quiet")
ds <- try(new(GDALRaster, filename_in), silent = TRUE)
pop_error_handler()
if (is(ds, "Rcpp_GDALRaster"))
```
to suppress unnecessary error message from GDAL when `filename_in` does not already exists or is not a raster dataset.
=> inspectDataset() and warp(): wrap checks of raster dataset open in quiet error handler

R/RcppExports.R, R/geom.R, man/g_envelope.Rd, src/RcppExports.cpp, src/geom_api.cpp, src/geom_api.h, tests/testthat/test-geom.R
The return order of xy coordinates is changed to `(xmin, xmax, ymin, ymax)`, as was documented and originally intended. This is a breaking change but is intended to match the return of `Geometry.GetEnvelope3D()` in the `osgeo.ogr` Python bindings. Fizes #725.
Also adds argument `as_3d`, optionally get the 3D envelope, wrapper of `OGR_G_GetEnvelope3D()` in the GDAL Geometry API returning `(xmin, xmax, ymin, ymax, zmin, zmax)`.
=> `g_envelope()`: fix order of xy coordinates in the returned envelope vector(s) and add argument `as_3d`

R/RcppExports.R, R/geom.R, man/g_unary_op.Rd, src/RcppExports.cpp, src/geom_api.cpp, src/geom_api.h, tests/testthat/test-geom.R
Wrapper of `OGR_G_DelaunayTriangulation()` in the GDAL Geometry API.
=> Add g_delaunay_triangulation(): return a Delaunay triangulation of the vertices of the input geometry

R/geom.R, R/s3_methods.R, inst/extdata/test_ogr_geojson_mixed_timezone.geojson, man/g_binary_op.Rd, man/g_make_valid.Rd, man/g_swap_xy.Rd, man/g_transform.Rd, man/g_unary_op.Rd, man/g_wk2wk.Rd, src/RcppExports.cpp, src/geom_api.cpp, src/geom_api.h, tests/testthat/test-geom.R, tests/testthat/test-s3_methods.R
This PR affects the Geometry API `g_*()` functions. It improves handling of OGR NULL geometries:
* Make I/O consistent with the data type specifications for class `GDALVector`
* `g_wk2wk()` should round trip when `NA` / `NULL` are involved
* `print.OGRFeature()` and `print.OGRFeatureSet()` should denote NULL geometries
TODO:
=> Geom API: fix the handling of OGR NULL geometries

R/display.R
I see a speed up by avoiding vapply, as far as I can tell the result is identical. 
```R
library(gdalraster)
elev_file <- system.file("extdata/storml_elev.tif", package="gdalraster")
ds <- new(GDALRaster, elev_file)
vals <- read_ds(ds) %/% 61
vv <- sort(unique(na.omit(vals)))
tab <- cbind(val = vv, 
col = scales::rescale(t(col2rgb(hcl.colors(length(vv))))))
system.time(plot_raster(vals, col_tbl = tab, interpolate = F))
```
Prior, I saw more like
```
```
(I'm doing this a *lot* with Sentinel 2 classifications, so it's really noticeable)
=> performance improve for display via col_tbl

tests/testthat/test-GDALVector-class.R
Range domains with only the min or max not supported in FileGDB (https://github.com/OSGeo/gdal/pull/12571)
=> Remove tests for range field domains in ESRI file geodatabase having only the min or max value

R/gdal_create.R, tests/testthat/test-gdal_create.R
Test the `create()` and `createCopy()` R public interface to the wrapper functions in src/gdal_exp.cpp (with existing tests also in test-gdal_exp.R), and improves input validation.
=> Add tests in test-gdal_create.R

R/gdalraster_proc.R, man/pixel_extract.Rd, src/gdalraster.cpp, tests/testthat/test-gdalraster_proc.R
...
@param xy A two-column numeric matrix or two-column data frame of geospatial
coordinates (x, y), or a vector for a single point (x, y), in the same
spatial reference system as `raster`. Can also be given as a data frame with
three or more columns, in which the first column must be a vector of point
IDs (`character` or `numeric`), and the second and third columns must contain
the geospatial coordinates (x, y).
...
@param as_data_frame Logical value, `TRUE` to return output as a data frame.
The default is to return a numeric matrix unless point IDs are present in
the first column of `xy` given as a data frame. In that latter case, the
output will always be a data frame with the point IDs in the first column.
@returns A numeric matrix or data frame of pixel values with number of rows …
=> `pixel_extract()`: support optional point IDs in the first column of an input data frame and add argument `as_data_frame`

R/RcppExports.R, man/srs_convert.Rd, src/RcppExports.cpp, src/srs_api.cpp, tests/testthat/test-srs_api.R
arguments `multiline`, `iindent_width` and `schema ` were not passed correctly in the call to `OSRExportToPROJJSON()`
=> srs_to_projjson(): fix passing options in the API call

tests/testthat/test-GDALVector-class.R
Removes a test that was missed in #741, none/infinite min or max is not supported in ESRI file geodaatbase (https://github.com/OSGeo/gdal/issues/12564)
=> Remove a test for datetime range domain with no min or max value in ESRI file geodatabase

NEWS.md, src/gdalraster.cpp
PR to accurately report on null-driver, described as "" by GetDriverLongName and GetDriverShortName. 
Fixes #759 
(I toyed with a test for this but a bit too challenging - not sure if we can use sourceCpp to set one up? By creating a GDAL MULTDIMRASTER with OpenEx, then casting a MDArray to classic).
=> report no driver when driver null (fixes 759)

src/gdalraster.cpp, src/gdalraster.h
=> GDALRaster: call GDALReleaseDataset() in the destructor instead of GDALClose() if dataset is non-shared

inst/COPYRIGHTS, src/gdalraster.cpp, src/gdalraster.h, src/gdalvector.cpp, src/gdalvector.h
Adds `#include <gdal_priv.h>` so the copy of `ARE_REAL_EQUAL()` is also removed here.
=> `setGDALDatasetH_()` in classes `GDALRaster` and `GDALVector`: check shared flag of incoming GDALDatasetH and set the `m_shared` member variable

R/ogr_reproject.R, man/ogr_reproject.Rd, tests/testthat/test-ogr_reproject.R, vignettes/vector-api-overview.Rmd
This PR only affects tests and example code involving `ogr_reproject()`. In the tests and examples, it disables the Arrow code path for ogr2ogr (cf. https://gdal.org/en/stable/programs/ogr2ogr.html#known-issues) and avoids use of virtual file systems. This is only to simplify, and eliminate possible contributing factors while attempting to resolve errors described in #769.
=> Disable the Arrow code path for ogr2ogr and avoid virtual file systems in examples and tests for ogr_reproject() while attempting to fix #769

R/ogr_reproject.R, man/ogr_reproject.Rd, tests/testthat/test-GDALVector-class.R, tests/testthat/test-gdal_exp.R, tests/testthat/test-ogr_reproject.R, vignettes/vector-api-overview.Rmd
This PR adds to #770. Mainly, these PRs together:
* temporarily disable GDAL's Arrow API code path in tests and example code where `gdalraster::ogr2ogr()` is used, and avoid the use of any virtual file systems while attempting to fix https://github.com/USDAForestService/gdalraster/issues/769
* BLAS/LAPACK are not involved in vector reprojection, so the CRAN errors may be false positive
* cf. https://lists.osgeo.org/pipermail/gdal-dev/2025-August/060834.html
* CRAN apparently will not provide the output of `ldd libgdal.so` on the affected system to verify there are not 2 PROJ versions linked
* at time of writing, the CRAN check errors on systems with alternative BLAS/LAPACK implementations have not been reproduced elsewhere
* cf. https://github.com/USDAForestService/gdalraster/issues/769#is …
=> Potential mitigations for #769

_pkgdown.yml, vignettes/articles/vector-api-overview.Rmd
in its original form as of the version 2.1.0 release
=> Doc: move vector-api-overview from vignette to a web article

R/display.R
CRAN compliance <https://stat.ethz.ch/pipermail/r-package-devel/2025q3/011901.html>
=> plot_raster(): use on.exit for par reset

R/RcppExports.R, R/cmb_table.R, R/gdal_cli.R, R/gdalalg.R, R/gdalraster.R, R/gdalvector.R, R/running_stats.R, R/vsifile.R, man/CmbTable-class.Rd, man/GDALAlg-class.Rd, man/GDALRaster-class.Rd, man/GDALVector-class.Rd, man/RunningStats-class.Rd, man/VSIFile-class.Rd, man/gdal_cli.Rd, man/gdal_version.Rd, man/gdalraster-package.Rd, src/RcppExports.cpp, src/gdal_exp.cpp, src/gdalalg.cpp, src/gdalalg.h, tests/testthat/test-GDALAlg-class.R, tests/testthat/test-gdal_cli.R, vignettes/articles/use-gdal-cli-from-r.Rmd
Includes code fixes and improvements, minor new functionality, and documentation updates. Some documentation changes related to formatting in .Rd files are applied throughout the package for consistency, but code changes in this PR affect only the CLI bindings:
* ensure algorithm names originating in `Rcpp::CharacterVector` are always passed explicitly in GDAL C API calls as `const char *`, via `get_cstring()` method of `Rcpp::String`
* fix clang compiler warning from `-Wunused-const-variable`
* improve input validation in class `GDALAlg`
* add `gdal_global_reg_names()`: return a character vector containing the names of the algorithms in the GDAL global algorithm registry
* allow example code in the documentation to execute in checks only if names are returned from the global algorithm …
=> Multiple updates for the gdal CLI bindings

src/gdalraster.cpp, src/rcpp_util.cpp, src/rcpp_util.h
Detect loaded namespaces and try to be compatible.
=> Try to be compatible with sf and terra in whether GDAL error level emits an R warning (but they differ)

src/ogr_util.cpp
Fixes some functions that could return without removing the `CPLQuietErrorHandler` if opening the input dataset failed.
=> Ensure that the global error handler is restored when the input dataset cannot be opened in some OGR management functions

R/RcppExports.R, R/geom.R, man/g_factory.Rd, man/g_query.Rd, man/g_unary_op.Rd, man/g_wk2wk.Rd, src/RcppExports.cpp, src/geom_api.cpp, src/geom_api.h, tests/testthat/test-geom.R
`g_geom_count()` returns the number of elements in a geometry or number of geometries in container. Only geometries of type `Polygon[25D]`, `MultiPoint[25D]`, `MultiLineString[25D]`, `MultiPolygon[25D]` or `GeometryCollection[25D]` may return a valid value. Other geometry types will silently return `0`.
`g_get_geom()` fetches a geometry from a geometry container (1-based indexing). For a polygon, requesting the first sub-geometry returns the exterior ring (`sub_geom_idx = 1`), and the interior rings are returned for `sub_geom_idx > 1`.
=> Add g_geom_count() and g_get_geom()

R/RcppExports.R, R/geom.R, man/bbox_to_wkt.Rd, man/g_unary_op.Rd, src/RcppExports.cpp, src/geom_api.cpp, src/geom_api.h, tests/testthat/test-geom.R
`g_unary_union()` returns the union of all components of a single geometry. Usually used to convert a collection into the smallest set of polygons that cover the same area. See https://postgis.net/docs/ST_UnaryUnion.html for more details. Requires GDAL >= 3.7.
=> Add g_unary_union(), wrapper for OGR_G_UnaryUnion()

R/RcppExports.R, R/geom.R, man/g_util.Rd, src/RcppExports.cpp, src/geom_api.cpp, src/geom_api.h, tests/testthat/test-geom.R
`g_normalize()` organizes the elements, rings, and coordinate order of
geometries in a consistent way, so that geometries that represent the same
object can be easily compared. Wrapper of `OGR_G_Normalize()` in the GDAL
API. Requires GDAL >= 3.3. Normalization ensures the following:
* Lines are oriented to have smallest coordinate first (apart from duplicate
endpoints)
* Rings start with their smallest coordinate (using XY ordering)
* Polygon shell rings are oriented clockwise, and holes counter-clockwise
* Collection elements are sorted by their first coordinate
=> Add g_normalize(), wrapper for OGR_G_Normalize()
