tests/testthat/test-gdal_exp.R, tests/testthat/test-proj.R, tests/testthat/test-transform.R
add/update tests for:
R/proj.R
src/gdal_exp.cpp
src/trasnform.cpp
=> update unit tests

NEWS.md, R/RcppExports.R, R/gdal_rat.R, man/buildRAT.Rd, man/displayRAT.Rd, src/RcppExports.cpp, src/gdal_exp.cpp, src/gdalraster.cpp, src/gdalraster.h
internal function used in `buildRAT()` to compute the set of unique pixel values and their counts
=> add _value_count()

NEWS.md, R/RcppExports.R, src/RcppExports.cpp, src/gdal_exp.cpp, src/ogr_util.cpp, src/ogr_util.h, tests/testthat/test-ogr_util.R
`_ogr_ds_exists()`
`_ogr_layer_exists()`
`_ogr_layer_create()`
`_ogr_layer_delete()`
`_ogr_field_index()`
`_ogr_field_create()`
=> add OGR utility functions for internal use

src/gdal_exp.cpp
=> buildVRT(): make file list explicit null terminated

DESCRIPTION, NEWS.md, src/gdalraster.cpp, src/gdalraster.h
get the GDAL dataset handle for internal use
=> Add `GDALRaster::_getGDALDatasetH()`

tests/testthat/test-gdalraster_proc.R
=> Update test for multiband output in `calc()`

src/gdal_exp.cpp
=> ogrinfo(): dsn placeholder in GDALVectorInfoOptions struct

src/gdal_exp.cpp
Still trying to get consistent behavior with GDAL 3.8 vs 3.9 beta, wrt argument passing in the `GDALVectorInfoOptions` struct. This seems related to the new `GDALArgumentParser` class in 3.9 beta.
see #322 #323
=> ogrinfo(): make arg passing in GDALVectorInfoOptions depend on GDAL version

DESCRIPTION, NEWS.md, R/RcppExports.R, man/ogr2ogr.Rd, src/RcppExports.cpp, src/gdal_exp.cpp, src/gdalraster.h, tests/testthat/test-gdal_exp.R
Support open options on the source dataset.
=> ogr2ogr(): add argument open_options

src/gdalraster.cpp
fixing memory leaks detected by valgrind
=> class GDALRaster: free allocated string buffers in getDefaultRAT() and info()

DESCRIPTION, NEWS.md, R/gdalraster.R, man/GDALRaster-class.Rd, src/gdalraster.cpp, src/gdalraster.h, tests/testthat/test-GDALRaster-class.R
=> GDALRaster::infoOptions is now empty by default

R/ogr_define.R, R/ogr_manage.R, man/ogr_define.Rd, tests/testthat/test-ogr_manage.R
Additional tests of OGR utility functions for managing vector data sources.
=> Improve test coverage for ogr_manage  and ogr_define

DESCRIPTION, NEWS.md, R/gdalraster_proc.R, man/DEFAULT_DEM_PROC.Rd, tests/testthat/test-gdalraster_proc.R
`"color-relief"` instead of `"color_relief"`, fixes #428
=> Fix the mode name for color-relief in DEFAULT_DEM_PROC

DESCRIPTION, NEWS.md, R/gdalvector.R, R/ogr_manage.R, man/GDALVector-class.Rd, man/ogr_manage.Rd, src/gdalvector.cpp, src/gdalvector.h, tests/testthat/test-GDALVector-class.R
`$startTransaction()`, `$commitTransaction()`, `$rollbackTransaction()`
=> Add transactions support in class `GDALVector`

DESCRIPTION, NEWS.md, R/gdal_create.R, R/gdalraster.R, man/GDALRaster-class.Rd, man/create.Rd, man/createCopy.Rd, src/gdal_exp.cpp, src/gdalraster.cpp, src/gdalraster.h, tests/testthat/test-GDALRaster-class.R
Most formats do not support adding new bands, but those that do support include `MEM` and `VRT`.
=> Add GDALRaster::addBand(): add a new band if the format supports it

R/RcppExports.R, man/srs_find_epsg.Rd, src/wkt_conv.cpp
as documented (instead of empty string or 0-row data frame)
=> srs_find_epsg(): return NULL if no matches were found

DESCRIPTION, NEWS.md, R/RcppExports.R, man/ogr2ogr.Rd, src/gdal_exp.cpp
```r
if (has_spatialite()) {
ynp_dissolved <- file.path(tempdir(), "ynp_fires_dissolve.gpkg")
sql <- "SELECT ig_year, ST_Union(geom) AS geom FROM mtbs_perims GROUP BY ig_year"
args <- c("-sql", sql, "-dialect", "SQLITE")
args <- c(args, "-nlt", "MULTIPOLYGON", "-nln", "dissolved_on_year")
ogr2ogr(src, ynp_dissolved, cl_arg = args)
}
```
=> Doc: ogr2ogr(): add example for dissolve features based on a shared attribute value

DESCRIPTION, NEWS.md, src/transform.cpp, src/transform.h
Header for src/transform.cpp. Minor code cleanup with no behavior changes.
=> Add src/transform.h

DESCRIPTION, NEWS.md, R/RcppExports.R, man/inv_project.Rd, man/transform_xy.Rd, src/transform.cpp, src/wkt_conv.cpp, src/wkt_conv.h
previously required SRS arguments in WKT format
=> transform_xy() and inv_project(): accept SRS arguments in any format supported by srs_to_wkt()

NEWS.md, R/gdalvector.R, man/GDALVector-class.Rd, src/gdalvector.cpp, tests/testthat/test-GDALVector-class.R
New feature for type of geometry return.
A followup from #538
=> add option "BBOX" for returnGeomAs

src/rcpp_util.cpp, src/rcpp_util.h
also adds `MIN_INTEGER64` and `MAX_INTEGER64` defines from the bit64 package src/integer64.h
=> Validate input columns in the data frame-to-matrix internal C++ functions

R/gdalvector.R, man/GDALVector-class.Rd, src/gdalvector.cpp, src/gdalvector.h, tests/testthat/test-GDALVector-class.R
Prints information about the vector layer to the console (no return value, called for that side effect only).
=> Add GDALVector::info()

R/cmb_table.R, R/gdalraster.R, R/gdalvector.R, R/running_stats.R, R/vsifile.R, tests/testthat/test-CmbTable-class.R, tests/testthat/test-GDALRaster-class.R, tests/testthat/test-GDALVector-class.R, tests/testthat/test-RunningStats-class.R, tests/testthat/test-VSIFile-class.R
minimal for now but we can add more items if it seems useful
=> Add S4 show methods for the Rcpp exposed classes

R/display.R
=> plot_raster: avoid integer overflow 

R/gdalvector.R, tests/testthat/test-GDALVector-class.R
=> Display the SQL statement in S4 show() for a GDALVector object open on a SQL layer

R/cmb_table.R, R/gdal_helpers.R, R/gdalraster.R, R/gdalvector.R, R/running_stats.R, R/vsifile.R, src/cmb_table.cpp, src/cmb_table.h, src/gdalraster.cpp, src/gdalraster.h, src/gdalvector.cpp, src/gdalvector.h, src/running_stats.cpp, src/running_stats.h, src/vsifile.cpp, src/vsifile.h, tests/testthat/test-CmbTable-class.R, tests/testthat/test-GDALRaster-class.R, tests/testthat/test-RunningStats-class.R, tests/testthat/test-VSIFile-class.R
=> Refactor S4 show() for the exposed C++ classes

R/RcppExports.R, R/geom.R, man/g_query.Rd, man/gdalraster-package.Rd, src/RcppExports.cpp, src/geom_api.cpp, src/geom_api.h, tests/testthat/test-geom.R
`g_is_3D()` checks whether a geometry has Z coordinates.
`g_is_measured()` checks whether a geometry is measured (has M values).
=> Geom: add `g_is_3D()` and `g_is_measured()`

R/transform.R, man/inv_project.Rd, man/transform_xy.Rd, src/transform.cpp, tests/testthat/test-transform.R
see https://github.com/OSGeo/gdal/pull/11819
close #628
=> transform_xy() / inv_project(): account for behavior change at GDAL 3.11

src/geom_api.cpp
Fixes for recently introduced changes in `g_transform()` (#672), and `g_geodesic_area()`, `g_geodesic_length()` (#671)
=> Geom API: avoid memory leak in certain cases where importing an SRS definition fails

src/vsifile.cpp, src/vsifile.h, tests/testthat/test-VSIFile-class.R
=> VSIFile::read(): nbytes should accept integer64

R/s3_methods.R, man/plot.OGRFeature.Rd, man/plot.OGRFeatureSet.Rd
@param main The main title (on top).
=> Add argument main to the S3 plot methods for OGRFeature and OGRFeatureSet

R/gdalvector.R, R/ogr_define.R, man/GDALVector-class.Rd, man/ogr_define.Rd, src/gdalvector.h, tests/testthat/test-GDALVector-class.R, tests/testthat/test-ogr_proc.R, tests/testthat/test-ogr_reproject.R
As used in class `GDALVector` and helper function `ogr_def_layer()` .
=> Change default geometry column name to 'geom'

vignettes/vector-api-overview.Rmd
=> Edit vector-api-overview
